---
- name: Install and start Nginx
  hosts: all
  become: root
  
  tasks: 
	- name: Update apt cache
    	  apt:
     	    update_cache: yes
	  
 	- name: Upgrade all packages
      	  apt:
            upgrade: dist
       	    autoremove: yes
            autoclean: yes
	    
    	- name: Install Apache, Python, and additional packages
      	  apt:
       	    name: "{{ item }}"
            state: present
          loop:
	    - apache2
      	    - python3
      	    - python3-pip

	- name: Install Nginx
	  apt: 
	    name: nginx
	    state: present
	
	- name: Start Nginx
	  apt:
	    name: nginx
	    state: started
